// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/schedule": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/schedule";
  };
  "schedule/Schedule.tsx": {
    id: "schedule/Schedule";
    page: "/schedule";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "schedule/Schedule": typeof import("./app/schedule/Schedule.tsx");
};